spring:
  application:
    name: urcarcher-be

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://urcarcher.kro.kr:3306/urcarcher
    username: root
    password: lastwindow

  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-request-size: 30MB
      max-file-size: 10MB

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: lastwindow
    enabled: true
  port: 8443


google:
   api:
     key: AIzaSyDjWcnM0idooe--a1VIYhNpoVBCcNu7s-4
jwt:
  secret: 95ad92b98db7213f0e6558fe697e7d1ab4444df10ab5361629e03aabcf4d4db0464d942925c88e5584d42336a319f765e6279408182a4aba1aa129ae281a101c


